# Generated by Django 5.2.5 on 2025-08-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_categories_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название уроков')),
                ('content', models.CharField(max_length=255, verbose_name='Описание уроков')),
            ],
        ),
    ]
