# Generated by Django 5.2.5 on 2025-08-28 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_listexercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='listexercises',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='learning.categories'),
        ),
    ]
