# Generated by Django 5.2.5 on 2025-08-30 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_listexercises_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listexercises',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='learning.categories'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(verbose_name='Задания')),
                ('listcat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listtask', to='learning.listexercises')),
            ],
        ),
    ]
