# Generated by Django 5.2.5 on 2025-08-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_alter_listexercises_cat_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='example_output',
            field=models.CharField(default=1, verbose_name='Пример выхода'),
            preserve_default=False,
        ),
    ]
